'use client';
import {useEffect,useRef,useState} from 'react';
import {LogOut,Package,ScanLine,RefreshCw,Trash2,CreditCard,Settings,Plus,Camera,CheckCircle2,AlertCircle,DoorOpen,Tag,ShoppingBag,ChevronRight,ShieldCheck} from 'lucide-react';
import {firebaseAuth} from '../lib/firebase';
import {RecaptchaVerifier, signInWithPhoneNumber, onAuthStateChanged, signOut} from 'firebase/auth';
import {api} from '../lib/api';

const emptyProduct={barcode:'',name:'',brand:'',category:'',mrp:'',sellingPrice:'',manufacturingDate:'',expiryDate:'',quantity:1,barcodeSource:'camera',detailsSource:'ocr',ocrText:''};

function money(v){return `₹${Number(v||0).toFixed(2)}`}
function esc(v){return String(v??'')}
function toast(setToast,msg,type='ok'){setToast({msg,type});setTimeout(()=>setToast(null),3200)}

export default function Home(){
 const [user,setUser]=useState(null),[loading,setLoading]=useState(true),[tab,setTab]=useState('dashboard'),[toastState,setToast]=useState(null);
 const [phone,setPhone]=useState(''),[otp,setOtp]=useState(''),[confirmation,setConfirmation]=useState(null),[loginBusy,setLoginBusy]=useState(false),[profile,setProfile]=useState({name:'',email:'',shopName:''});
 useEffect(()=>onAuthStateChanged(firebaseAuth,async fu=>{
   if(fu){try{const token=await fu.getIdToken();localStorage.setItem('smartshop_token',token);const saved=localStorage.getItem('smartshop_user');if(saved)setUser(JSON.parse(saved));}catch{}}else{localStorage.removeItem('smartshop_token');}
   setLoading(false);
 }),[]);
 async function refreshToken(){const fu=firebaseAuth.currentUser;if(fu){const t=await fu.getIdToken(true);localStorage.setItem('smartshop_token',t)}}
 async function sendOtp(){
  if(phone.replace(/\D/g,'').length<10)return toast(setToast,'Enter a valid 10-digit mobile number.','error');
  setLoginBusy(true);try{
   if(!window.recaptchaVerifier)window.recaptchaVerifier=new RecaptchaVerifier(firebaseAuth,'recaptcha-container',{size:'invisible'});
   const result=await signInWithPhoneNumber(firebaseAuth,`+91${phone.replace(/\D/g,'').slice(-10)}`,window.recaptchaVerifier);setConfirmation(result);toast(setToast,'OTP sent to your mobile.');
  }catch(e){try{window.recaptchaVerifier?.clear();window.recaptchaVerifier=null}catch{}toast(setToast,e.message||'Could not send OTP.','error')}finally{setLoginBusy(false)}
 }
 async function verifyOtp(){setLoginBusy(true);try{const credential=await confirmation.confirm(otp);const token=await credential.user.getIdToken(true);localStorage.setItem('smartshop_token',token);setProfile(p=>({...p,name:credential.user.displayName||'',email:credential.user.email||''}));toast(setToast,'Mobile verified. Complete your shop profile.');}catch(e){toast(setToast,e.message||'Invalid OTP.','error')}finally{setLoginBusy(false)}}
 async function finishLogin(){
  if(!profile.name.trim()||!profile.shopName.trim())return toast(setToast,'Owner name and shop name are required.','error');
  setLoginBusy(true);try{await refreshToken();const fu=firebaseAuth.currentUser;const d=await api('loginFirebase',{firebaseUid:fu.uid,phone:fu.phoneNumber,email:profile.email,name:profile.name,shopName:profile.shopName});setUser(d.user);localStorage.setItem('smartshop_user',JSON.stringify(d.user));setTab('dashboard');toast(setToast,'Welcome to your shop.');}catch(e){toast(setToast,e.message,'error')}finally{setLoginBusy(false)}}
 async function logout(){await signOut(firebaseAuth);localStorage.removeItem('smartshop_user');setUser(null);setConfirmation(null);setOtp('');}
 if(loading)return <div className="loginPage"><div className="spinner"/></div>;
 if(!firebaseAuth.currentUser)return <LoginScreen phone={phone} setPhone={setPhone} otp={otp} setOtp={setOtp} confirmation={confirmation} profile={profile} setProfile={setProfile} busy={loginBusy} sendOtp={sendOtp} verifyOtp={verifyOtp} finishLogin={finishLogin} toastState={toastState}/>;
 if(!user)return <ProfileScreen profile={profile} setProfile={setProfile} finishLogin={finishLogin} busy={loginBusy} toastState={toastState}/>;
 return <ShopApp user={user} setUser={setUser} tab={tab} setTab={setTab} logout={logout} toastState={toastState} setToast={setToast}/>;
}

function LoginScreen({phone,setPhone,otp,setOtp,confirmation,profile,setProfile,busy,sendOtp,verifyOtp,finishLogin,toastState}){
 return <div className="loginPage"><div className="loginCard glass">
  <div className="loginLogo"><ShieldCheck size={28}/></div><div className="eyebrow">SMART SHOP · SECURE ACCESS</div><h1>Run your shop smarter.</h1><p className="muted">Barcode scanning, RFID inventory, exit checkout and sales — backed by MongoDB Atlas.</p>
  {!confirmation?<><div className="field"><label>Mobile number</label><div className="row"><div className="tag" style={{padding:'12px 10px'}}>+91</div><input className="input" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="98765 43210" inputMode="numeric"/></div></div><div id="recaptcha-container"/><button className="btn primary" style={{width:'100%'}} onClick={sendOtp} disabled={busy}>{busy?'Sending…':'Send OTP'}</button></>:!firebaseAuth.currentUser?<><div className="field"><label>6-digit OTP</label><input className="input" value={otp} onChange={e=>setOtp(e.target.value)} maxLength={6} inputMode="numeric" placeholder="123456"/></div><button className="btn primary" style={{width:'100%'}} onClick={verifyOtp} disabled={busy}>{busy?'Verifying…':'Verify mobile'}</button><button className="btn ghost" style={{width:'100%',marginTop:8}} onClick={()=>location.reload()}>Change number</button></>:<ProfileFields profile={profile} setProfile={setProfile} finishLogin={finishLogin} busy={busy}/>}<div className="small muted" style={{marginTop:16}}>Firebase Phone Authentication handles the SMS OTP. Configure your Firebase authorized domain before production use.</div>{toastState&&<div className={`alert ${toastState.type==='error'?'error':'ok'}`} style={{marginTop:12}}>{toastState.msg}</div>}
 </div></div>
}
function ProfileFields({profile,setProfile,finishLogin,busy}){return <><div className="field"><label>Owner name</label><input className="input" value={profile.name} onChange={e=>setProfile({...profile,name:e.target.value})} placeholder="Your name"/></div><div className="field"><label>Email <span className="muted">(optional)</span></label><input className="input" type="email" value={profile.email} onChange={e=>setProfile({...profile,email:e.target.value})} placeholder="owner@example.com"/></div><div className="field"><label>Shop name</label><input className="input" value={profile.shopName} onChange={e=>setProfile({...profile,shopName:e.target.value})} placeholder="My Shop"/></div><button className="btn primary" style={{width:'100%'}} onClick={finishLogin} disabled={busy}>{busy?'Opening shop…':'Continue to shop'}</button></>}
function ProfileScreen({profile,setProfile,finishLogin,busy,toastState}){return <div className="loginPage"><div className="loginCard glass"><div className="loginLogo"><ShoppingBag/></div><div className="eyebrow">PROFILE SETUP</div><h1>Finish your shop profile.</h1><ProfileFields profile={profile} setProfile={setProfile} finishLogin={finishLogin} busy={busy}/>{toastState&&<div className={`alert ${toastState.type==='error'?'error':'ok'}`} style={{marginTop:12}}>{toastState.msg}</div>}</div></div>}

function ShopApp({user,setUser,tab,setTab,logout,toastState,setToast}){
 const [dashboard,setDashboard]=useState(null),[events,setEvents]=useState([]),[busy,setBusy]=useState(false),[product,setProduct]=useState({...emptyProduct}),[scanner,setScanner]=useState(false),[manualBarcode,setManualBarcode]=useState('');
 const load=async()=>{try{const d=await api('dashboard',{shopId:user.shopId},'GET');setDashboard(d)}catch(e){toast(setToast,e.message,'error')}};
 const loadEvents=async()=>{try{const d=await api('exitEvents',{shopId:user.shopId},'GET');setEvents(d.events||[])}catch(e){toast(setToast,e.message,'error')}};
 useEffect(()=>{load();loadEvents();const t=setInterval(loadEvents,4000);return()=>clearInterval(t)},[]);
 async function saveProduct(){setBusy(true);try{if(!product.barcode||!product.name||!product.sellingPrice)return toast(setToast,'Barcode, product name and selling price are required.','error');const d=await api('saveProduct',{...product,shopId:user.shopId,shopName:user.shopName,userId:user.userId});toast(setToast,`Product saved. ${d.remainingRfids||0} RFID tag(s) still need assignment.`);setProduct({...emptyProduct});setScanner(false);setTab('dashboard');await load()}catch(e){toast(setToast,e.message,'error')}finally{setBusy(false)}}
 async function removeProduct(barcode){if(!confirm(`Delete ${barcode} from ${user.shopName}?`))return;try{await api('deleteProduct',{shopId:user.shopId,barcode});toast(setToast,'Product deleted.');load()}catch(e){toast(setToast,e.message,'error')}}
 async function sell(barcode){try{const d=await api('recordSale',{shopId:user.shopId,userId:user.userId,shopName:user.shopName,barcode,quantity:1});toast(setToast,`Sale recorded: ${money(d.total)}`);load()}catch(e){toast(setToast,e.message,'error')}}
 async function pay(){if(!events.length)return;setBusy(true);try{const ids=events.map(e=>e.eventId);const d=await api('payExitEvents',{shopId:user.shopId,shopName:user.shopName,userId:user.userId,eventIds:ids,firebaseUid:firebaseAuth.currentUser?.uid});toast(setToast,`Payment recorded: ${money(d.total)} · ${d.paidEvents} item(s)`);await loadEvents();await load()}catch(e){toast(setToast,e.message,'error')}finally{setBusy(false)}}
 async function removeEvent(eventId){try{await api('removeExitEvent',{shopId:user.shopId,eventId});toast(setToast,'Exit item removed and stock restored.');loadEvents();load()}catch(e){toast(setToast,e.message,'error')}}
 async function saveExitCount(v){try{const d=await api('updateExitCount',{shopId:user.shopId,exitCount:v});setUser({...user,exitCount:d.exitCount});localStorage.setItem('smartshop_user',JSON.stringify({...user,exitCount:d.exitCount}));toast(setToast,'Exit door count updated.')}catch(e){toast(setToast,e.message,'error')}}
 return <div className="appShell"><header className="topbar"><div className="topbarInner"><div className="brand"><div className="brandMark"><Package size={20}/></div><span>Smart Shop</span></div><div className="userChip"><div className="avatar">{(user.name||'O')[0]}</div><span>{user.shopName}</span><button className="btn ghost" onClick={logout}><LogOut size={16}/></button></div></div></header>
 <main className="container"><div className="hero"><div className="glass heroCard"><div className="eyebrow">SHOP COMMAND CENTER</div><h1>Everything under one roof.</h1><p>Track products, assign one RFID tag per physical unit, watch exit doors in real time and turn detections into paid sales.</p><div className="row" style={{marginTop:18}}><button className="btn primary" onClick={()=>setTab('scanner')}><ScanLine size={17}/> Add product</button><button className="btn" onClick={()=>{load();loadEvents()}}><RefreshCw size={17}/> Refresh</button></div></div><div className="glass miniCard"><div><div className="eyebrow">LIVE EXIT QUEUE</div><div className="miniNumber">{events.length}</div><div className="muted">item{events.length===1?'':'s'} waiting for payment</div></div><button className="btn" onClick={()=>setTab('checkout')} style={{marginTop:18}}>Open checkout <ChevronRight size={16}/></button></div></div>
 <div className="tabs">{[['dashboard','Overview',Package],['scanner','Add Product',ScanLine],['checkout','Exit Checkout',CreditCard],['settings','Settings',Settings]].map(([id,label,I])=><button key={id} className={`tab ${tab===id?'active':''}`} onClick={()=>setTab(id)}><I size={15} style={{verticalAlign:'-3px',marginRight:6}}/>{label}</button>)}</div>
 {tab==='dashboard'&&<Dashboard dashboard={dashboard} onSell={sell} onDelete={removeProduct} onRefresh={load}/>} {tab==='scanner'&&<Scanner product={product} setProduct={setProduct} scanner={scanner} setScanner={setScanner} manualBarcode={manualBarcode} setManualBarcode={setManualBarcode} onSave={saveProduct} busy={busy}/>} {tab==='checkout'&&<Checkout events={events} onPay={pay} onRemove={removeEvent} busy={busy}/>} {tab==='settings'&&<SettingsPanel user={user} onSave={saveExitCount}/>} </main>{toastState&&<div className="toast"><div className="row">{toastState.type==='error'?<AlertCircle size={18} color="#fb7185"/>:<CheckCircle2 size={18} color="#5eead4"/>}<span>{toastState.msg}</span></div></div>}</div>
}

function Dashboard({dashboard,onSell,onDelete,onRefresh}){return <><div className="grid4">{[['Products',dashboard?.stats?.products||0,Package],['Sales',dashboard?.stats?.salesCount||0,ShoppingBag],['Units sold',dashboard?.stats?.salesUnits||0,Tag],['Sales amount',money(dashboard?.stats?.salesAmount),CreditCard]].map(([l,v,I])=><div className="glass stat" key={l}><div className="statLabel"><I size={15} style={{verticalAlign:'-3px',marginRight:6}}/>{l}</div><div className="statValue">{v}</div></div>)}</div><div className="layout"><div className="glass card"><div className="cardTitle"><div><h2>My Shop Products</h2><div className="small muted">{dashboard?.shopName||'Loading…'} · RFID status per product</div></div><button className="btn" onClick={onRefresh}><RefreshCw size={15}/></button></div>{!dashboard?<div className="empty">Loading inventory…</div>:!dashboard.products?.length?<div className="empty">No products yet. Use Add Product to create your first item.</div>:dashboard.products.map(p=><div className="product" key={p.barcode}><div className="productTop"><div><div className="productName">{esc(p.name||'Unnamed product')}</div><div className="muted small">{esc(p.brand)} · {esc(p.category)} · {esc(p.barcode)}</div></div><div className="price">{money(p.sellingPrice)}</div></div><div><span className="tag">Stock {p.quantity}</span><span className={`tag ${p.rfidStatus==='ASSIGNED'?'ok':'warn'}`}>{p.rfidStatus}</span><span className="tag">RFID {p.assignedRfids||0}/{p.quantity}</span></div><div className="actions"><button className="btn" onClick={()=>onSell(p.barcode)} disabled={!p.quantity}>Sell 1</button><button className="btn danger" onClick={()=>onDelete(p.barcode)}>Delete</button></div></div>)}</div><div className="glass card"><div className="cardTitle"><div><h2>How the flow works</h2><div className="small muted">Same physical RFID workflow as your current setup.</div></div></div>{[['1','Scan barcode','Capture the product barcode with the browser camera.'],['2','Read details','OCR helps fill MRP, MFD and EXP.'],['3','Assign RFID','ESP8266 scans one tag for every physical unit.'],['4','Exit detection','ESP32 Exit Door scans the tag and reduces stock.'],['5','Pay','Detected items stay in the queue until paid.']].map(x=><div className="row" style={{alignItems:'flex-start',marginBottom:16}} key={x[0]}><div className="tag ok">{x[0]}</div><div><b>{x[1]}</b><div className="small muted" style={{marginTop:3}}>{x[2]}</div></div></div>)}</div></div></>}

function Scanner({product,setProduct,scanner,setScanner,manualBarcode,setManualBarcode,onSave,busy}){const video=useRef(null),stream=useRef(null),reader=useRef(null);const [mode,setMode]=useState('idle'),[status,setStatus]=useState('Ready'),[ocr,setOcr]=useState(false);
 useEffect(()=>()=>{stream.current?.getTracks().forEach(t=>t.stop())},[]);
 async function start(){setScanner(true);setMode('barcode');setStatus('Starting camera…');try{const facing=window.matchMedia('(max-width:700px)').matches?'environment':'user';stream.current=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:facing},width:{ideal:1920},height:{ideal:1080}},audio:false});video.current.srcObject=stream.current;await video.current.play();setStatus('Point the barcode inside the frame.')}catch(e){setStatus(`Camera error: ${e.message}`)}}
 async function decode(){setStatus('Scanning barcode…');try{const {BrowserMultiFormatReader}=await import('@zxing/browser');reader.current=new BrowserMultiFormatReader();const result=await reader.current.decodeOnceFromVideoElement(video.current);const code=result?.getText?.()||result?.text||'';if(!code)throw new Error('No barcode detected');setProduct(p=>({...p,barcode:code,barcodeSource:'camera'}));setStatus(`Barcode detected: ${code}`);setMode('details');}catch(e){setStatus('Could not read the barcode. Move closer, reduce glare and try again.')}}
 async function startDetails(){setMode('details');setStatus('Place MRP / MFD / EXP inside the box.');}
 async function captureOCR(){if(!video.current?.videoWidth)return;setOcr(true);setStatus('Running OCR…');try{const canvas=document.createElement('canvas');canvas.width=video.current.videoWidth;canvas.height=video.current.videoHeight;canvas.getContext('2d').drawImage(video.current,0,0,canvas.width,canvas.height);const {createWorker}=await import('tesseract.js');const worker=await createWorker('eng');const {data}=await worker.recognize(canvas);await worker.terminate();const text=data.text||'';setProduct(p=>({...p,ocrText:text,detailsSource:'ocr',...extractOCR(text)}));setStatus('OCR complete. Check the extracted fields below.');setMode('form');}catch(e){setStatus(`OCR error: ${e.message}`);setMode('form')}finally{setOcr(false)}}
 function skip(){setMode('form');setStatus('Enter product details manually.')} 
 if(!scanner)return <div className="glass card"><div className="cardTitle"><div><h2>Add a product</h2><div className="muted small">Barcode → OCR → product details → RFID assignment</div></div></div><div className="scannerWrap"><div className="empty"><Camera size={34}/><h3>Camera scanner</h3><p>Use your laptop front camera or mobile rear camera.</p><button className="btn primary" onClick={start}><ScanLine size={16}/> Start scanning</button></div><div className="alert"><b>RFID quantity rule</b><p className="small muted">If quantity is 3, the system creates 3 pending RFID assignments. The ESP8266 assigns them one-by-one.</p></div></div></div>;
 return <div className="glass card">{mode!=='form'?<div className="scannerWrap"><div><div className="camera"><video ref={video} muted playsInline autoPlay/><div className="scanBox"/>{mode==='barcode'&&<div className="scanLine"/>}</div><div className="alert" style={{marginTop:10}}>{status}</div><div className="actions">{mode==='barcode'?<button className="btn primary" onClick={decode} disabled={ocr}><ScanLine size={16}/> Capture barcode</button>:<button className="btn primary" onClick={captureOCR} disabled={ocr}>{ocr?'Reading…':'Capture & read details'}</button>}<button className="btn" onClick={skip}>Skip OCR</button></div></div><div><div className="cardTitle"><div><h2>{mode==='barcode'?'Step 1 · Barcode':'Step 2 · Package text'}</h2><div className="small muted">{mode==='barcode'?'Keep the entire barcode inside the frame.':'Place MRP/MFD/EXP clearly inside the frame.'}</div></div></div><div className="alert"><b>Detected barcode</b><div style={{fontSize:22,fontFamily:'Space Grotesk',marginTop:7}}>{product.barcode||'—'}</div></div></div></div>:<ProductForm product={product} setProduct={setProduct} onSave={onSave} busy={busy} onBack={()=>setMode('details')}/>}</div>}
function ProductForm({product,setProduct,onSave,busy,onBack}){const f=(k,v)=>setProduct({...product,[k]:v});return <><div className="cardTitle"><div><div className="eyebrow">PRODUCT DETAILS</div><h2>Review before saving</h2><div className="small muted">RFID assignments are created automatically from quantity.</div></div><button className="btn" onClick={onBack}>Back</button></div><div className="two"><div className="field"><label>Barcode</label><input className="input" value={product.barcode} onChange={e=>f('barcode',e.target.value)}/></div><div className="field"><label>Quantity</label><input className="input" type="number" min="1" value={product.quantity} onChange={e=>f('quantity',Math.max(1,Number(e.target.value)))}/></div></div><div className="two"><div className="field"><label>Product name</label><input className="input" value={product.name} onChange={e=>f('name',e.target.value)} placeholder="Tic Tac Mint"/></div><div className="field"><label>Brand</label><input className="input" value={product.brand} onChange={e=>f('brand',e.target.value)} placeholder="Brand"/></div></div><div className="three"><div className="field"><label>Category</label><input className="input" value={product.category} onChange={e=>f('category',e.target.value)} placeholder="Grocery"/></div><div className="field"><label>MRP</label><input className="input" value={product.mrp} onChange={e=>f('mrp',e.target.value)} placeholder="₹20"/></div><div className="field"><label>Selling price *</label><input className="input" value={product.sellingPrice} onChange={e=>f('sellingPrice',e.target.value)} placeholder="15"/></div></div><div className="two"><div className="field"><label>Manufacturing date</label><input className="input" value={product.manufacturingDate} onChange={e=>f('manufacturingDate',e.target.value)} placeholder="08/2026"/></div><div className="field"><label>Expiry date</label><input className="input" value={product.expiryDate} onChange={e=>f('expiryDate',e.target.value)} placeholder="08/2028"/></div></div><div className="field"><label>OCR text</label><textarea className="textarea" value={product.ocrText} onChange={e=>f('ocrText',e.target.value)} placeholder="OCR result…"/></div><div className="alert ok"><b>RFID plan:</b> {product.quantity} physical unit(s) → {product.quantity} RFID tag(s) required.</div><button className="btn primary" style={{width:'100%',marginTop:12}} onClick={onSave} disabled={busy}>{busy?'Saving…':'Save product & create RFID assignments'}</button></>}

function extractOCR(text){const clean=text.replace(/\n+/g,'\n');const money=clean.match(/(?:MRP|MAXIMUM RETAIL PRICE|RS\.?|₹)\s*[:.-]?\s*₹?\s*(\d+(?:\.\d{1,2})?)/i);const dates=[...clean.matchAll(/\b(\d{1,2}[\/-]\d{1,2}[\/-]\d{2,4}|\d{1,2}[\/-]\d{2,4}|\d{2}[.-]\d{2}[.-]\d{2,4})\b/g)].map(x=>x[1]);const mfd=clean.match(/(?:MFD|MFG|MANUFACTURED|MANUFACTURING|PKD|PACKED)[^\d]{0,15}(\d{1,2}[\/-]\d{1,2}[\/-]\d{2,4}|\d{1,2}[\/-]\d{2,4}|\d{2}[.-]\d{2}[.-]\d{2,4})/i);const exp=clean.match(/(?:EXP|EXPIRY|USE BY|BEST BEFORE)[^\d]{0,15}(\d{1,2}[\/-]\d{1,2}[\/-]\d{2,4}|\d{1,2}[\/-]\d{2,4}|\d{2}[.-]\d{2}[.-]\d{2,4})/i);return {mrp:money?.[1]||'',manufacturingDate:mfd?.[1]||dates[0]||'',expiryDate:exp?.[1]||dates[1]||''}}

function Checkout({events,onPay,onRemove,busy}){const total=events.reduce((s,e)=>s+Number(e.price||0),0);return <div className="layout"><div className="glass card"><div className="cardTitle"><div><div className="eyebrow">REAL-TIME RFID EXIT</div><h2>Detected products</h2><div className="small muted">ESP32 exit readers post directly to the Express API.</div></div><span className="tag ok">LIVE</span></div>{!events.length?<div className="empty"><DoorOpen size={34}/><p>No products are waiting at the exit.</p></div>:events.map(e=><div className="exitItem" key={e.eventId}><div><b>{e.productName||'Unnamed product'}</b><div className="small muted">Exit {e.exitNo} · RFID {e.rfidUid} · {e.barcode}</div></div><div style={{textAlign:'right'}}><div className="price">{money(e.price)}</div><button className="btn danger" style={{marginTop:7}} onClick={()=>onRemove(e.eventId)}><Trash2 size={14}/> Remove</button></div></div>)}</div><div className="glass card"><div className="eyebrow">CHECKOUT</div><div className="total"><span>Total</span><span>{money(total)}</span></div><p className="small muted">Payment changes all selected WAITING_PAYMENT events to PAID and creates sales records in MongoDB.</p><button className="btn primary" style={{width:'100%',marginTop:14}} disabled={!events.length||busy} onClick={onPay}><CreditCard size={17}/> {busy?'Processing…':'PAID · Generate bill'}</button></div></div>}
function SettingsPanel({user,onSave}){const [n,setN]=useState(user.exitCount||1);return <div className="glass card"><div className="cardTitle"><div><div className="eyebrow">SHOP CONFIGURATION</div><h2>Exit doors</h2><div className="muted small">Configure how many ESP32/ESP8266 exit readers this shop uses.</div></div></div><div className="two"><div className="field"><label>Number of exit doors</label><input className="input" type="number" min="1" max="20" value={n} onChange={e=>setN(Math.min(20,Math.max(1,Number(e.target.value))))}/></div><div style={{display:'flex',alignItems:'end'}}><button className="btn primary" style={{width:'100%',marginBottom:13}} onClick={()=>onSave(n)}>Save configuration</button></div></div><div className="alert"><b>MongoDB collections</b><div className="small muted" style={{marginTop:5}}>users · products · rfidAssignments · rfidInventory · sales · exitEvents</div></div></div>}
